name: Test Pull Request

on: pull_request

env:
  MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
  SECRET: ${{ secrets.SECRET }}
  TEST_BEARER_TOKEN: ${{ secrets.TEST_BEARER_TOKEN }}

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Test API
        run: npm run test-api