name: Test

on:
  push:
    branches:
      - main

jobs:
  Perform Testing:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout Project
      - uses: actions/checkout@v3

      - name: Setup Node
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Say hello
        run: |
          echo "Hello World!"