name: Test

on:
  push:
    branches:
      - main

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Create ENV file
        run: |
          touch .env
          echo MONGO_TEST_URI=${{ secrets.MONGO_TEST_URI }} >> .env
          echo SECRET=${{ secrets.SECRET }} >> .env
          echo TEST_BEARER_TOKEN = ${{ TEST_BEARER_TOKEN }} >> .env

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test-api